#include "token.h"

static const char *token_names[TOK_COUNT] = {
    [TOK_INT_LIT]      = "int literal",
    [TOK_FLOAT_LIT]    = "float literal",
    [TOK_STRING_LIT]   = "string literal",
    [TOK_CSTRING_LIT]  = "cstring literal",
    [TOK_CHAR_LIT]     = "char literal",
    [TOK_IDENT]        = "identifier",
    [TOK_TYPE_VAR]     = "type variable",
    [TOK_LET]          = "'let'",
    [TOK_MUT]          = "'mut'",
    [TOK_STRUCT]       = "'struct'",
    [TOK_UNION]        = "'union'",
    [TOK_MODULE]       = "'module'",
    [TOK_NAMESPACE]    = "'namespace'",
    [TOK_IMPORT]       = "'import'",
    [TOK_FROM]         = "'from'",
    [TOK_AS]           = "'as'",
    [TOK_EXTERN]       = "'extern'",
    [TOK_PRIVATE]      = "'private'",
    [TOK_MATCH]        = "'match'",
    [TOK_WITH]         = "'with'",
    [TOK_IF]           = "'if'",
    [TOK_THEN]         = "'then'",
    [TOK_ELSE]         = "'else'",
    [TOK_FOR]          = "'for'",
    [TOK_IN]           = "'in'",
    [TOK_LOOP]         = "'loop'",
    [TOK_BREAK]        = "'break'",
    [TOK_CONTINUE]     = "'continue'",
    [TOK_RETURN]       = "'return'",
    [TOK_SOME]         = "'some'",
    [TOK_TRUE]         = "'true'",
    [TOK_FALSE]        = "'false'",
    [TOK_NONE]         = "'none'",
    [TOK_VOID]         = "'void'",
    [TOK_ALLOC]        = "'alloc'",
    [TOK_FREE]         = "'free'",
    [TOK_SIZEOF]       = "'sizeof'",
    [TOK_DEFAULT]      = "'default'",
    [TOK_PRINT]        = "'print'",
    [TOK_EPRINT]       = "'eprint'",
    [TOK_FPRINT]       = "'fprint'",
    [TOK_SPRINT]       = "'sprint'",
    [TOK_PLUS]         = "'+'",
    [TOK_MINUS]        = "'-'",
    [TOK_STAR]         = "'*'",
    [TOK_SLASH]        = "'/'",
    [TOK_PERCENT]      = "'%'",
    [TOK_AMP]          = "'&'",
    [TOK_PIPE]         = "'|'",
    [TOK_CARET]        = "'^'",
    [TOK_TILDE]        = "'~'",
    [TOK_BANG]         = "'!'",
    [TOK_EQ]           = "'='",
    [TOK_EQEQ]        = "'=='",
    [TOK_BANGEQ]       = "'!='",
    [TOK_LT]          = "'<'",
    [TOK_GT]           = "'>'",
    [TOK_LTEQ]        = "'<='",
    [TOK_GTEQ]        = "'>='",
    [TOK_LTLT]        = "'<<'",
    [TOK_GTGT]        = "'>>'",
    [TOK_AMPAMP]       = "'&&'",
    [TOK_PIPEPIPE]     = "'||'",
    [TOK_ARROW]        = "'->'",
    [TOK_DOTDOT]       = "'..'",
    [TOK_DOT]          = "'.'",
    [TOK_COLONCOLON]   = "'::'",
    [TOK_COLON]        = "':'",
    [TOK_COMMA]        = "','",
    [TOK_QUESTION]     = "'?'",
    [TOK_SEMICOLON]    = "';'",
    [TOK_LPAREN]       = "'('",
    [TOK_RPAREN]       = "')'",
    [TOK_LBRACKET]     = "'['",
    [TOK_RBRACKET]     = "']'",
    [TOK_LBRACE]       = "'{'",
    [TOK_RBRACE]       = "'}'",
    [TOK_NEWLINE]      = "newline",
    [TOK_INDENT]       = "indent",
    [TOK_DEDENT]       = "dedent",
    [TOK_HASH_IF]      = "'#if'",
    [TOK_HASH_ELSE]    = "'#else'",
    [TOK_HASH_ELSE_IF] = "'#else if'",
    [TOK_HASH_END]     = "'#end'",
    [TOK_EOF]          = "end of file",
    [TOK_ERROR]        = "error",
};

const char *token_kind_name(TokenKind kind) {
    if (kind >= 0 && kind < TOK_COUNT && token_names[kind]) {
        return token_names[kind];
    }
    return "unknown";
}
